INSERT INTO item (Category, Brand, Item) VALUES ('Apparel', 'Nike', 'Running Shoes');
INSERT INTO item (Category, Brand, Item) VALUES ('Apparel', 'Nike', 'Basketball Shoes');
INSERT INTO item (Category, Brand, Item) VALUES ('Apparel', 'Nike', 'Sports Jacket');
INSERT INTO item (Category, Brand, Item) VALUES ('Apparel', 'Nike', 'Sports Shorts');
INSERT INTO item (Category, Brand, Item) VALUES ('Apparel', 'H&M', 'Blouse');
INSERT INTO item (Category, Brand, Item) VALUES ('Apparel', 'H&M', 'Jacket');
INSERT INTO item (Category, Brand, Item) VALUES ('Apparel', 'H&M', 'Sunglasses');
INSERT INTO item (Category, Brand, Item) VALUES ('Apparel', 'Uniqlo', 'Sweater');
INSERT INTO item (Category, Brand, Item) VALUES ('Apparel', 'Uniqlo', 'Scarf');
INSERT INTO item (Category, Brand, Item) VALUES ('Apparel', 'Uniqlo', 'Bag');
INSERT INTO item (Category, Brand, Item) VALUES ('Apparel', 'Adidas', 'T-Shirt');
INSERT INTO item (Category, Brand, Item) VALUES ('Apparel', 'Adidas', 'Shoes');
INSERT INTO item (Category, Brand, Item) VALUES ('Apparel', 'Adidas', 'Track Pants');
INSERT INTO item (Category, Brand, Item) VALUES ('Electronics', 'Apple', 'Headphones');
INSERT INTO item (Category, Brand, Item) VALUES ('Electronics', 'Apple', 'iPhone');
INSERT INTO item (Category, Brand, Item) VALUES ('Electronics', 'Apple', 'MacBook');
INSERT INTO item (Category, Brand, Item) VALUES ('Electronics', 'Huawei', 'Laptop');
INSERT INTO item (Category, Brand, Item) VALUES ('Electronics', 'Huawei', 'Tablet');
INSERT INTO item (Category, Brand, Item) VALUES ('Electronics', 'Samsung', 'Galaxy Phone');
INSERT INTO item (Category, Brand, Item) VALUES ('Electronics', 'Samsung', 'Galaxy Tab');
INSERT INTO item (Category, Brand, Item) VALUES ('Electronics', 'Samsung', 'Smartwatch');
INSERT INTO item (Category, Brand, Item) VALUES ('Electronics', 'Sony', 'Camera');
INSERT INTO item (Category, Brand, Item) VALUES ('Electronics', 'Sony', 'Smart TV');
INSERT INTO item (Category, Brand, Item) VALUES ('Electronics', 'Sony', 'Sound System');
INSERT INTO item (Category, Brand, Item) VALUES ('Electronics', 'Sony', 'Soundbar');
INSERT INTO item (Category, Brand, Item) VALUES ('Outdoor Adventure', 'Columbia', 'Sleeping Bag');
INSERT INTO item (Category, Brand, Item) VALUES ('Outdoor Adventure', 'Columbia', 'Hiking Boots');
INSERT INTO item (Category, Brand, Item) VALUES ('Outdoor Adventure', 'Columbia', 'Camping Chair');
INSERT INTO item (Category, Brand, Item) VALUES ('Outdoor Adventure', 'Patagonia', 'Lantern');
INSERT INTO item (Category, Brand, Item) VALUES ('Outdoor Adventure', 'Patagonia', 'Portable Grill');
INSERT INTO item (Category, Brand, Item) VALUES ('Outdoor Adventure', 'Patagonia', 'Water Bottle');
INSERT INTO item (Category, Brand, Item) VALUES ('Outdoor Adventure', 'The North Face', 'Tent');
INSERT INTO item (Category, Brand, Item) VALUES ('Outdoor Adventure', 'The North Face', 'Backpack');
INSERT INTO item (Category, Brand, Item) VALUES ('Outdoor Adventure', 'The North Face', 'Camping Stove');